/*
 * TIMER0_config.h
 *
 *  Created on: Feb 12, 2024
 *      Author: Omar Gamal El-Kady
 */

#ifndef MCAL_TIMERS_TIMER0_TIMER0_CONFIG_H_
#define MCAL_TIMERS_TIMER0_TIMER0_CONFIG_H_

#define TIMER0_WG_MODE             TIMER0_WG_MODE_NORMAL

#define TIMER0_PRESCALER           TIMER0_PRESCALER_256

#define TIMER0_COM_MODE_NON_PWM            TIMER0_COM_MODE_NON_PWM_NORMAL

#define TIMER0_INTERRUPT_MODE      TIMER0_OVFINT




#endif /* MCAL_TIMERS_TIMER0_TIMER0_CONFIG_H_ */
